Ecomm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name='cart'

urlpatterns = [
    path('/<p>',views.addtocart,name='addtocart'),
    path('cartview', views.cartview, name='cartview'),
    path('remove_cart/<p>', views.remove_cart, name='remove_cart'),
    path('add_cart/<p>', views.add_cart, name='add_cart'),
    path('delete_cart/<p>', views.delete_cart, name='delete_cart'),
    path('order', views.order, name='order'),
    path('order_view', views.order_view, name='order_view'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/<p>', views.products, name='products'),
    path('details/<p>', views.details, name='details'),
    path('register', views.u_register, name='register'),
    path('login', views.u_login, name='login'),
    path('logout', views.u_logout, name='logout'),

]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

# Create your models here.

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def total(self):
        return self.product.price * self.quantity

class Account(models.Model):
    acc_no=models.IntegerField()
    acc_type=models.CharField(max_length=30)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acc_no)

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    amount=models.IntegerField()
    no_of_item = models.IntegerField()
    address = models.TextField()
    phone = models.IntegerField()
    order_status = models.CharField(max_length=30, default='pending')
    delivery_status = models.CharField(max_length=30, default='pending')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def Total(self):
        return self.no_of_item * self.product.price

cart/views.py
from django.shortcuts import render,HttpResponse
from django.contrib.auth.decorators import login_required
from shop.models import Product
from .models import Cart,Account,Order

# Create your views here.
@login_required
def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    amount=0
    for i in cart:
        amount +=i.quantity * i.product.price
    return render(request,template_name='cart.html',context={'cart':cart,'total':amount})

@login_required
def addtocart(request,p):
    pr = Product.objects.get(name=p)
    u=request.user
    try:
        cart = Cart.objects.get(product=pr, user=u)
        if (cart.quantity<pr.stock):
            cart.quantity +=1
            cart.save()
            return cartview(request)
    except:
        if (pr.stock >0):
            cart=Cart.objects.create(product=pr,user=u,quantity=1)
            cart.save()
            return cartview(request)
        else:
            return HttpResponse('Currently Not available')
    return cartview(request)

@login_required()
def add_cart(request,p):
    u=request.user
    pr=Product.objects.get(name=p)

    try:
        cart=Cart.objects.get(user=u,product=pr)
        if (cart.quantity<cart.product.stock):
            cart.quantity +=1
            cart.save()
            return cartview(request)
    except:
        HttpResponse('exceeded the stock')
    return cartview(request)

@login_required()
def remove_cart(request,p):
    u=request.user
    pr=Product.objects.get(name=p)
    cart = Cart.objects.get(user=u, product=pr)
    try:
        if cart.quantity >1:
            cart.quantity -=1
            cart.save()
            return cartview(request)
        else:
            cart.delete()
            return cartview(request)
    except:
        return cartview(request)

    
@login_required
def delete_cart(request,p):
    u=request.user
    pr=Product.objects.get(name=p)
    try:
        cart=Cart.objects.get(user=u,product=pr)
        cart.delete()
        return cartview(request)
    except:
        return cartview(request)

@login_required
def order(request):
    if request.method=='POST':
        p=request.POST['ph']
        a=request.POST['ad']
        u=request.user
        acc=request.POST['acc']
        cart=Cart.objects.filter(user=u)
        total=0

        try:
            ac = Account.objects.get(acc_no=acc)
            for i in cart:
                total +=i.quantity * i.product.price
            if ac.amount > total:
                ac.amount -=total
                ac.save()
                for i in cart:
                    pr=Order.objects.create(user=u,product=i.product,amount=i.product.price,no_of_item=i.quantity,address=a,phone=p,order_status='ordered')
                    pr.save()
                    msg='item ordered'
                cart.delete()
                return render(request,template_name='order_clar.html',context={'msg':msg})

            else:
                print(ac.amount)
                msg='Insufficient Balance'
                return render(request,template_name='order_clar.html',context={'msg':msg})

        except:
            msg='Invalid bank details'
            return render(request, template_name='order_clar.html', context={'msg': msg})
    return render(request,template_name='order.html')

@login_required
def order_view(request):
    u=request.user
    items=Order.objects.filter(user=u)
    return render(request,template_name='order_view.html',context={'j':items})

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{%static 'css/style.css'%}" type="text/css" rel="stylesheet">
</head>
<body>
<div class="container">
    <center>
        <img src="{% static 'images/lo.png'%}" height="50px;" width="50px;">
    </center>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'shop:home'%}">MyShop</a>
        <button type="button" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-togg">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbar-togg">
                <ul class="navbar-nav me-auto mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    {%if user.is_authenticated%}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button"  data-bs-toggle="dropdown">all items</a>
                        <ul class="dropdown-menu">
                            {%for i in links%}
                            <li><a class="dropdown-item" href="{%url 'shop:products' i.category %}">{{i.category}}</a></li>
                            {%endfor%}
                        </ul>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:order_view'%}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'shop:logout'%}">logout</a>
                    </li>
                    {%else%}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'shop:login'%}">login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'shop:register'%}">Register</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
         {%if user.is_authenticated%}
         <form class="d-flex" >
             <input type="text" name="search" placeholder="Search here.." class="from-control">
             <button type="submit" class="btn btn-outline-light btn-success" >Search</button>
         </form>
        <p class="text-light"> {{ user.username}}</p>
        <a href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping text-warning" style="margin-left:10px;"><sup class="text-danger"> {{count}}</sup></i></a>
        {%else%}
        <h6 class="text-light">Guest</h6>
        {%endif%}
    </div>
</nav>

{%block body%}
{%endblock%}

<div class="footer text-center">
    <div class="text-light pt-3">
        <i class="fa-regular fa-copyright"></i>
        <a class="" style="text-decoration:none;">Copyright</a>
    </div>
</div>
</body>
</html>

templates/cart.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<div class="container-fluid">
    <div class="row m-3">

        <div class="col-md-7">
            <table class="table table-bordered">
               <tr>
                    <th class="text-center" colspan="7">Cart item</th>
               </tr>
                {%for i in cart%}
                <tr>
                    <td><img src="{{i.product.image.url}}" width="50px;" height="50px;"></td>
                    <td class="fw-bold">{{i.product.name}}</td>
                    <td class="fw-bold">Quantity: <b>{{i.quantity}}</b></td>
                    <td class="fw-bold">Price : <b>{{i.product.price}}</b></td>
                    <td class="fw-bold">total :{{i.total}} </td>
                    <td style="display:block;" class="fs-5">
                        <a href="{% url 'cart:add_cart' i.product.name %}"><i class="fa-solid fa-plus text-danger"></i></a>
                        <a href="{% url 'cart:remove_cart' i.product.name %}"><i class="fa-solid fa-minus text-danger"></i></a>
                        <a href="{% url 'cart:delete_cart' i.product.name %}"><i class="fa-solid fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {%endfor%}
            </table>
        </div>

        <div class="col-md-5">
            <table class="table table-bordered">
                <tr>
                    <th class="text-center">Checkout</th>
                </tr>
                <tr>
                    <td class="fw-bold">Total Amount : <b>{{total}}</b></td>
                </tr>
            </table>
            <a class="btn btn-danger" href="{% url 'cart:order' %}">place order</a>
            <a class="btn btn-success" style="position:absolute; right:42px;" href="{%url 'shop:home' %}">Continue shopping</a>
        </div>

    </div>
</div>
{%endblock%}

templates/details.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<div class="container-fluid m-3" style="margin-bottom:80px;">
    <div class="row">
        <div class="col-md-3">
            <img src="{{p.image.url}}" width="100%" height="400px;">
        </div>

        <div class="col-md-9 p-2">
            <div>
                <h5>{{p.name}}</h5>
                <p>{{p.desc}}</p>
            </div>
            <div class="text-center">
                <a class="btn btn-outline-light btn-success" href="{% url 'cart:addtocart' p.name %}">Add to cart</a>
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/home.html
{% extends 'base.html'%}
{%load static%}
{%block body%}
<div class="container-fluid bg-light">
    <img src="{%static 'images/banne.jpg'%}" height="400px" width="100%;" class="pt-2 pb-2">
</div>
<div class="container-fluid bg-info pt-2">
    <p style="text-alignment:justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<div class="container-fluid" style="margin-bottom:60px;">
    <div class="row">
        {%for i in item%}
        <div class="col-md-3 p-3">
            <div class="box-element">
                <img src="{{i.image.url}}" class="card-img-top card-image" width="100%;" height="300px;">
                <div class="card-body">
                    <h4 class="card-title text-center">{{i.category}}</h4>
                </div>
                <center>
                    <a class="btn btn-primary btn-outline-light" href="{% url 'shop:products' i.category %}">Products</a>
                </center>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

templates/login.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<div class="container-fluid">
    <center>
        <form method="post" style="width:60%;">
            {%csrf_token%}
            <div class="mb-3">
                <label class="form-label">Username</label>
                <input type="text" name="uname" placeholder="Enter username.." class="form-control">
            </div>
             <div class="mb-3">
                <label class="form-label">Password</label>
                <input type="password" name="pass" placeholder="Enter Password.." class="form-control">
            </div>
            <button class="btn btn-outline-light btn-info">Login</button>
        </form>
    </center>
</div>
{%endblock%}

templates/order.html
{%extends 'base.html'%}
{%block body%}
<div class="container-fluid">
    <center>
        <form method="post" style="width:60%;">
            {%csrf_token%}
            <div class="mb-3">
                <label class="form-label">Account number :</label>
                <input class="form-control" name="acc" type="number">
            </div>
            <div class="mb-3">
                <label class="form-label">Phone number :</label>
                <input class="form-control" name="ph" type="number">
            </div>
            <div class="mb-3">
                <label class="form-label">Address :</label>
                <input class="form-control" name="ad" type="text">
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </center>
</div>
{%endblock%}

templates/order_clar.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<center>
    <h5>{{msg}}</h5>
    <h6>Continue shopping</h6>
    <h3 class="text-primary">Thank You</h3>
</center>
{%endblock%}

templates/order_view.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<div class="m-2 text-center">
    <table class="table table-bordered">
        <tr class="text-center fw-bold">
            <th>Product</th>
            <th>Name</th>
            <th>price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Ordered On</th>
            <th>Delivery Status</th>
        </tr>
        {%for i in j%}
        <tr>
            <td><img src="{{i.product.image.url}}" height="50px;" width="50px;"></td>
            <td>{{i.product.name}}</td>
            <td>{{i.product.price}}</td>
            <td>{{i.no_of_item}}</td>
            <td>{{i.Total}}</td>
            <td>{{i.date_added}}</td>
            <td>{{i.delivery_status}}</td>
        </tr>
        {%endfor%}
    </table>
</div>
{%endblock%}

templates/product.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<div class="container-fluid mt-3">
    <img src="{{fei.image.url}}" width="100%;" height="450px;">
    <p class="p-2 bg-info mt-3">{{fei.desc}}</p>
</div>
<div class="container">
    <div class="row" style="margin-bottom:60px;">
        {%for i in p%}
        <div class="col-md-3">
            <div class="box-element m-2" style="height:400px;">
                <img src="{{i.image.url}}" class="card-img-top" height="250px;" width="100%">
                <div class="card-body text-center" style="height:80px;">
                    <h5 class="card-title">{{i.name}}</h5>
                </div>
                <div class="text-center" style="margin-bottom:5px;">
                    <a class="btn btn-outline-light btn-primary" href="{% url 'shop:details' i.name %}">Details</a>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

templates/register.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<div class="container-fluid" style="margin-bottom:60px;">
    <center>
        <h5 class="text-primary">Register yourself</h5>
        <form method="post" style="width:60%;">
            {%csrf_token%}
            <div class="mb-3">
                <label class="form-label">Username :</label>
                <input type="text" name="uname" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">password :</label>
                <input type="password" name="pass" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">confirm password :</label>
                <input type="password" name="cpass" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">First name :</label>
                <input type="text" name="fname" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Last name :</label>
                <input type="text" name="lname" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Email :</label>
                <input type="email" name="email" class="form-control">
            </div>
            <button class="btn btn-outline-light btn-info" type="submit">Register</button>
        </form>
    </center>
</div>
{%endblock%}